<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-31T13:26:23 CST" name="Suite" finished-at="2025-03-31T13:26:58 CST" duration-ms="34498">
    <groups>
      <group name="Purchase">
        <method signature="Test4.submitOrder(java.util.HashMap)[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" name="submitOrder" class="JavaSeleniumTest.temp1.Test4"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-03-31T13:26:23 CST" name="Test Test" finished-at="2025-03-31T13:26:58 CST" duration-ms="34498">
      <class name="JavaSeleniumTest.temp1.Test4">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:23 CST" name="launchApp" finished-at="2025-03-31T13:26:32 CST" duration-ms="8258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method is-config="true" signature="setup()[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:32 CST" name="setup" finished-at="2025-03-31T13:26:32 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:32 CST" name="submitOrder" data-provider="getData" finished-at="2025-03-31T13:26:40 CST" duration-ms="8674" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{country=India, productname=IPHONE 13 PRO, password=Iamking@000, email=anshika@gmail.com, username=anshika@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at JavaSeleniumTest.temp1.Test4.submitOrder(Test4.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:40 CST" name="tearDown" finished-at="2025-03-31T13:26:41 CST" duration-ms="616" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:41 CST" name="launchApp" finished-at="2025-03-31T13:26:48 CST" duration-ms="7178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:48 CST" name="submitOrder" data-provider="getData" finished-at="2025-03-31T13:26:57 CST" duration-ms="8863" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{country=India, productname=IPHONE 13 PRO, password=Iamking@000, username=shetty@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at JavaSeleniumTest.temp1.Test4.submitOrder(Test4.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="setup()[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:48 CST" name="setup" finished-at="2025-03-31T13:26:48 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:JavaSeleniumTest.temp1.Test4@73cd37c0]" started-at="2025-03-31T13:26:57 CST" name="tearDown" finished-at="2025-03-31T13:26:58 CST" duration-ms="607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- JavaSeleniumTest.temp1.Test4 -->
    </test> <!-- Test Test -->
  </suite> <!-- Suite -->
</testng-results>
